### ISSUE TITLE
generating docker-compose with rabbitmq microservices seems not to work

### ISSUE THREAD

**Issue by flefevre** [hipster-labs/generator-jhipster-spring-cloud-stream#30]
I created a gateway and a microservice with a rabbitmq.
When I follow the tutorial on microservice, after the following command in the gateway and in the microservice:

```
./mvnw package -Pprod verify jib:build
```

I created a root folder docker, in which I have executed the command

```
jhipster docker-compose
```

The generated files do not contain any item on rabbitmq.

So I have manually added

```
    mymicroserviceapp-rabbitmq:
        image: 'rabbitmq:3.6.2-management'
        ports:
            - 5672:5672
            - 15672:15672
```

with also a dependency in the microservice

```
    mymicroservice-app:
        image: 'cflacmsbinderlatest'
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://cflacmsbinder-mysql:3306/cflacmsbinder?useUnicode=true&characterEncoding=utf8&useSSL=false'
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        depends_on:
            - mymicroserviceapp-rabbitmq 
```

But badly when starting the apps

```
docker-compose up -d
```

the gateway is ok
the mymicroserviceapp-rabbitmq is ok (checking http://localhost:15672)

The microservice linked to rabbitmq, do not start

> [fl218080@is233628 cflacdocker]$ docker-compose logs cflacmsbinder-app 
WARNING: The state variable is not set. Defaulting to a blank string.
Attaching to cflacdocker_cflacmsbinder-app_1
cflacmsbinder-app_1           | The application will start in 30s...
cflacmsbinder-app_1           | Picked up _JAVA_OPTIONS: -Xmx512m -Xms256m
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           |         ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
cflacmsbinder-app_1           |         ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
cflacmsbinder-app_1           |         ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
cflacmsbinder-app_1           |   ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
cflacmsbinder-app_1           |   ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
cflacmsbinder-app_1           |    ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | :: JHipster 🤓  :: Running Spring Boot 2.0.6.RELEASE ::
cflacmsbinder-app_1           | :: https://www.jhipster.tech ::
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | 2018-12-03 09:42:20.319  INFO 1 --- [           main] c.c.l.c.c.binder.CflacmsbinderApp        : The following profiles are active: prod,swagger
cflacmsbinder-app_1           | 2018-12-03 09:42:29.700  INFO 1 --- [           main] c.c.l.c.c.b.config.MetricsConfiguration  : Initializing Metrics Log reporting
cflacmsbinder-app_1           | 2018-12-03 09:42:34.890  INFO 1 --- [           main] c.c.l.c.c.binder.config.WebConfigurer    : Web application configuration, using profiles: prod
cflacmsbinder-app_1           | 2018-12-03 09:42:34.898  INFO 1 --- [           main] c.c.l.c.c.binder.config.WebConfigurer    : Web application fully configured
cflacmsbinder-app_1           | 2018-12-03 09:42:35.232  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
cflacmsbinder-app_1           | 2018-12-03 09:42:35.612  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
cflacmsbinder-app_1           | 2018-12-03 09:42:35.612  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
cflacmsbinder-app_1           | 2018-12-03 09:42:36.276  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
cflacmsbinder-app_1           | 2018-12-03 09:42:36.276  INFO 1 --- [           main] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
cflacmsbinder-app_1           | 2018-12-03 09:42:36.793  INFO 1 --- [           main] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
cflacmsbinder-app_1           | 2018-12-03 09:42:36.856  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
cflacmsbinder-app_1           | 2018-12-03 09:42:36.864  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
cflacmsbinder-app_1           | 2018-12-03 09:42:36.865  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
cflacmsbinder-app_1           | 2018-12-03 09:42:36.865  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Application is null : false
cflacmsbinder-app_1           | 2018-12-03 09:42:36.865  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
cflacmsbinder-app_1           | 2018-12-03 09:42:36.865  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
cflacmsbinder-app_1           | 2018-12-03 09:42:36.865  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
cflacmsbinder-app_1           | 2018-12-03 09:42:37.158  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : The response status is 200
cflacmsbinder-app_1           | 2018-12-03 09:42:37.161  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 5
cflacmsbinder-app_1           | 2018-12-03 09:42:37.173  INFO 1 --- [           main] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 12
cflacmsbinder-app_1           | 2018-12-03 09:42:37.191  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1543830157189 with initial instances count: 0
cflacmsbinder-app_1           | 2018-12-03 09:42:37.397  INFO 1 --- [           main] com.hazelcast.instance.AddressPicker     : [LOCAL] [dev] [3.9.4] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: []
cflacmsbinder-app_1           | 2018-12-03 09:42:37.398  INFO 1 --- [           main] com.hazelcast.instance.AddressPicker     : [LOCAL] [dev] [3.9.4] Prefer IPv4 stack is true.
cflacmsbinder-app_1           | 2018-12-03 09:42:37.401  WARN 1 --- [           main] com.hazelcast.instance.AddressPicker     : [LOCAL] [dev] [3.9.4] Could not find a matching address to start with! Picking one of non-loopback addresses.
cflacmsbinder-app_1           | 2018-12-03 09:42:37.419  INFO 1 --- [           main] com.hazelcast.instance.AddressPicker     : [LOCAL] [dev] [3.9.4] Picked [172.19.0.13]:5701, using socket ServerSocket[addr=/0.0.0.0,localport=5701], bind any local is true
cflacmsbinder-app_1           | 2018-12-03 09:42:37.463  INFO 1 --- [           main] com.hazelcast.system                     : [172.19.0.13]:5701 [dev] [3.9.4] Hazelcast 3.9.4 (20180420 - b8001d5) starting at [172.19.0.13]:5701
cflacmsbinder-app_1           | 2018-12-03 09:42:37.463  INFO 1 --- [           main] com.hazelcast.system                     : [172.19.0.13]:5701 [dev] [3.9.4] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.
cflacmsbinder-app_1           | 2018-12-03 09:42:37.463  INFO 1 --- [           main] com.hazelcast.system                     : [172.19.0.13]:5701 [dev] [3.9.4] Configured Hazelcast Serialization version: 1
cflacmsbinder-app_1           | 2018-12-03 09:42:38.031  INFO 1 --- [           main] c.h.s.i.o.impl.BackpressureRegulator     : [172.19.0.13]:5701 [dev] [3.9.4] Backpressure is disabled
cflacmsbinder-app_1           | 2018-12-03 09:42:39.306  INFO 1 --- [           main] com.hazelcast.instance.Node              : [172.19.0.13]:5701 [dev] [3.9.4] Creating TcpIpJoiner
cflacmsbinder-app_1           | 2018-12-03 09:42:39.673  INFO 1 --- [           main] c.h.s.i.o.impl.OperationExecutorImpl     : [172.19.0.13]:5701 [dev] [3.9.4] Starting 8 partition threads and 5 generic threads (1 dedicated for priority tasks)
cflacmsbinder-app_1           | 2018-12-03 09:42:39.813  INFO 1 --- [           main] c.h.internal.diagnostics.Diagnostics     : [172.19.0.13]:5701 [dev] [3.9.4] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.
cflacmsbinder-app_1           | 2018-12-03 09:42:39.822  INFO 1 --- [           main] com.hazelcast.core.LifecycleService      : [172.19.0.13]:5701 [dev] [3.9.4] [172.19.0.13]:5701 is STARTING
cflacmsbinder-app_1           | 2018-12-03 09:42:39.877  INFO 1 --- [           main] com.hazelcast.system                     : [172.19.0.13]:5701 [dev] [3.9.4] Cluster version set to 3.9
cflacmsbinder-app_1           | 2018-12-03 09:42:39.878  INFO 1 --- [           main] c.h.internal.cluster.ClusterService      : [172.19.0.13]:5701 [dev] [3.9.4] 
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | Members {size:1, ver:1} [
cflacmsbinder-app_1           | 	Member [172.19.0.13]:5701 - 946205fe-60d8-45ce-93ee-4387341a9dfe this
cflacmsbinder-app_1           | ]
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | 2018-12-03 09:42:39.937  INFO 1 --- [           main] com.hazelcast.core.LifecycleService      : [172.19.0.13]:5701 [dev] [3.9.4] [172.19.0.13]:5701 is STARTED
cflacmsbinder-app_1           | 2018-12-03 09:42:42.366  INFO 1 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f - Re-registering apps/CFLACMSBINDER
cflacmsbinder-app_1           | 2018-12-03 09:42:42.413  INFO 1 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f: registering service...
cflacmsbinder-app_1           | 2018-12-03 09:42:42.701  INFO 1 --- [tbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f - registration status: 204
cflacmsbinder-app_1           | 2018-12-03 09:42:46.142  INFO 1 --- [           main] c.h.h.HazelcastCacheRegionFactory        : Starting up HazelcastCacheRegionFactory
cflacmsbinder-app_1           | 2018-12-03 09:42:46.144  INFO 1 --- [           main] c.h.h.i.IHazelcastInstanceFactory        : Using existing HazelcastInstance [cflacmsbinder].
cflacmsbinder-app_1           | 2018-12-03 09:42:47.167  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
cflacmsbinder-app_1           | 2018-12-03 09:42:47.168  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
cflacmsbinder-app_1           | 2018-12-03 09:42:47.168  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
cflacmsbinder-app_1           | 2018-12-03 09:42:47.168  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
cflacmsbinder-app_1           | 2018-12-03 09:42:47.169  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
cflacmsbinder-app_1           | 2018-12-03 09:42:47.170  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
cflacmsbinder-app_1           | 2018-12-03 09:42:47.170  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
cflacmsbinder-app_1           | 2018-12-03 09:42:47.285  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
cflacmsbinder-app_1           | 2018-12-03 09:42:48.811 ERROR 1 --- [           main] .l.c.c.b.s.i.AuditPublicationServiceImpl : Attention be sure on the type of json/bytes message format
cflacmsbinder-app_1           | 2018-12-03 09:42:54.380  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
cflacmsbinder-app_1           | 2018-12-03 09:42:54.387  WARN 1 --- [           main] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
cflacmsbinder-app_1           | 2018-12-03 09:42:55.548  INFO 1 --- [           main] c.h.i.p.impl.PartitionStateManager       : [172.19.0.13]:5701 [dev] [3.9.4] Initializing cluster partition table arrangement...
cflacmsbinder-app_1           | 2018-12-03 09:42:57.359  INFO 1 --- [           main] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1543830177359, current=UP, previous=STARTING]
cflacmsbinder-app_1           | 2018-12-03 09:42:57.360  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f: registering service...
cflacmsbinder-app_1           | 2018-12-03 09:42:57.448  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f - registration status: 204
cflacmsbinder-app_1           | 2018-12-03 09:42:57.453  WARN 1 --- [nfoReplicator-0] o.s.b.a.amqp.RabbitHealthIndicator       : Rabbit health check failed
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:62)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:504)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:628)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:240)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1816)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1790)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1771)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.amqp.RabbitHealthIndicator.getVersion(RabbitHealthIndicator.java:48)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.amqp.RabbitHealthIndicator.doHealthCheck(RabbitHealthIndicator.java:44)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:84)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68)
cflacmsbinder-app_1           | 	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:103)
cflacmsbinder-app_1           | 	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:99)
cflacmsbinder-app_1           | 	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1382)
cflacmsbinder-app_1           | 	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
cflacmsbinder-app_1           | 	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
cflacmsbinder-app_1           | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
cflacmsbinder-app_1           | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
cflacmsbinder-app_1           | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
cflacmsbinder-app_1           | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
cflacmsbinder-app_1           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cflacmsbinder-app_1           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cflacmsbinder-app_1           | 	at java.lang.Thread.run(Thread.java:748)
cflacmsbinder-app_1           | Caused by: java.net.ConnectException: Connection refused (Connection refused)
cflacmsbinder-app_1           | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
cflacmsbinder-app_1           | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
cflacmsbinder-app_1           | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
cflacmsbinder-app_1           | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
cflacmsbinder-app_1           | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
cflacmsbinder-app_1           | 	at java.net.Socket.connect(Socket.java:589)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1102)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1054)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:994)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:457)
cflacmsbinder-app_1           | 	... 21 common frames omitted
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | 2018-12-03 09:42:57.471  WARN 1 --- [nfoReplicator-0] o.s.b.a.amqp.RabbitHealthIndicator       : Rabbit health check failed
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:62)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:504)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:628)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:240)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.core.RabbitTemplate.doExecute(RabbitTemplate.java:1816)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1790)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.core.RabbitTemplate.execute(RabbitTemplate.java:1771)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.amqp.RabbitHealthIndicator.getVersion(RabbitHealthIndicator.java:48)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.amqp.RabbitHealthIndicator.doHealthCheck(RabbitHealthIndicator.java:44)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:84)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68)
cflacmsbinder-app_1           | 	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:68)
cflacmsbinder-app_1           | 	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:103)
cflacmsbinder-app_1           | 	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:99)
cflacmsbinder-app_1           | 	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1382)
cflacmsbinder-app_1           | 	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117)
cflacmsbinder-app_1           | 	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101)
cflacmsbinder-app_1           | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
cflacmsbinder-app_1           | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
cflacmsbinder-app_1           | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
cflacmsbinder-app_1           | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
cflacmsbinder-app_1           | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cflacmsbinder-app_1           | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cflacmsbinder-app_1           | 	at java.lang.Thread.run(Thread.java:748)
cflacmsbinder-app_1           | Caused by: java.net.ConnectException: Connection refused (Connection refused)
cflacmsbinder-app_1           | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
cflacmsbinder-app_1           | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
cflacmsbinder-app_1           | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
cflacmsbinder-app_1           | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
cflacmsbinder-app_1           | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
cflacmsbinder-app_1           | 	at java.net.Socket.connect(Socket.java:589)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1102)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1054)
cflacmsbinder-app_1           | 	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:994)
cflacmsbinder-app_1           | 	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:457)
cflacmsbinder-app_1           | 	... 23 common frames omitted
cflacmsbinder-app_1           | 
cflacmsbinder-app_1           | 2018-12-03 09:42:57.702  WARN 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1543830177702, current=DOWN, previous=UP]
cflacmsbinder-app_1           | 2018-12-03 09:42:57.702  WARN 1 --- [nfoReplicator-0] c.n.discovery.InstanceInfoReplicator     : Ignoring onDemand update due to rate limiter
cflacmsbinder-app_1           | 2018-12-03 09:42:57.702  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f: registering service...
cflacmsbinder-app_1           | 2018-12-03 09:42:57.806  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_CFLACMSBINDER/cflacmsbinder:bfd39fc93ac1ef1eb274ea37ed64bf3f - registration status: 204
cflacmsbinder-app_1           | 2018-12-03 09:42:57.900  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
cflacmsbinder-app_1           | 2018-12-03 09:42:57.900  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
cflacmsbinder-app_1           | 2018-12-03 09:42:57.901  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
cflacmsbinder-app_1           | 2018-12-03 09:42:57.901  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application is null : false
cflacmsbinder-app_1           | 2018-12-03 09:42:57.901  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
cflacmsbinder-app_1           | 2018-12-03 09:42:57.901  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Application version is -1: false
cflacmsbinder-app_1           | 2018-12-03 09:42:57.901  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
cflacmsbinder-app_1           | 2018-12-03 09:42:57.964  INFO 1 --- [           main] c.c.l.c.c.b.config.LoggingConfiguration  : Initializing Logstash logging
cflacmsbinder-app_1           | 2018-12-03 09:42:57.984  INFO 1 --- [freshExecutor-0] com.netflix.discovery.DiscoveryClient    : The response status is 200
cflacmsbinder-app_1           | 2018-12-03 09:42:58.046  INFO 1 --- [           main] c.c.l.c.c.b.config.LoggingConfiguration  : Filtering metrics logs from all appenders except the LOGSTASH appender
cflacmsbinder-app_1           | 2018-12-03 09:42:58.161  INFO 1 --- [           main] c.c.l.c.c.binder.CflacmsbinderApp        : Started CflacmsbinderApp in 46.774 seconds (JVM running for 48.454)
cflacmsbinder-app_1           | 2018-12-03 09:42:58.175  INFO 1 --- [           main] c.c.l.c.c.binder.CflacmsbinderApp        : 
cflacmsbinder-app_1           | ----------------------------------------------------------
cflacmsbinder-app_1           | 	Application 'cflacmsbinder' is running! Access URLs:
cflacmsbinder-app_1           | 	Local: 		http://localhost:8081/
cflacmsbinder-app_1           | 	External: 	http://172.19.0.13:8081/
cflacmsbinder-app_1           | 	Profile(s): 	[prod, swagger]
cflacmsbinder-app_1           | ----------------------------------------------------------
cflacmsbinder-app_1           | 2018-12-03 09:42:58.176  INFO 1 --- [           main] c.c.l.c.c.binder.CflacmsbinderApp        : 
cflacmsbinder-app_1           | ----------------------------------------------------------
cflacmsbinder-app_1           | 	Config Server: 	Connected to the JHipster Registry running in Docker
cflacmsbinder-app_1           | ----------------------------------------------------------
cflacmsbinder-app_1           | 2018-12-03 09:42:59.958  INFO 1 --- [r.HealthMonitor] c.h.internal.diagnostics.HealthMonitor   : [172.19.0.13]:5701 [dev] [3.9.4] processors=8, physical.memory.total=31.0G, physical.memory.free=4.1G, swap.space.total=4.0G, swap.space.free=4.0G, heap.memory.used=125.9M, heap.memory.free=246.1M, heap.memory.total=372.0M, heap.memory.max=455.5M, heap.memory.used/total=33.84%, heap.memory.used/max=27.64%, minor.gc.count=38, minor.gc.time=1371ms, major.gc.count=4, major.gc.time=1313ms, load.process=0.00%, load.system=0.00%, load.systemAverage=11.67, thread.count=69, thread.peakCount=69, cluster.timeDiff=0, event.q.size=0, executor.q.async.size=0, executor.q.client.size=0, executor.q.query.size=0, executor.q.scheduled.size=0, executor.q.io.size=0, executor.q.system.size=0, executor.q.operations.size=0, executor.q.priorityOperation.size=0, operations.completed.count=1, executor.q.mapLoad.size=0, executor.q.mapLoadAllKeys.size=0, executor.q.cluster.size=0, executor.q.response.size=0, operations.running.count=0, operations.pending.invocations.percentage=0.00%, operations.pending.invocations.count=0, proxy.count=0, clientEndpoint.count=0, connection.active.count=0, client.connection.count=0, connection.count=0
cflacmsbinder-app_1           | 2018-12-03 09:43:02.503  WARN 1 --- [Du7QAfeCa65Yw-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer raised exception, processing can restart if the connection factory supports it. Exception summary: org.springframework.amqp.AmqpConnectException: java.net.ConnectException: Connection refused (Connection refused)

Any idea why?
Thanks

**Comment by flefevre** [comment]
Perhaps i do need to change something here

in the src/main/resources/config/application-prod.yml

`
spring:
    cloud:
        stream:
            default:
                contentType: application/json
            bindings:
                input:
                    destination: topic-jhipster
                output:
                    destination: topic-jhipster
                auditPublisher:
                    destination: topic-audit
                auditConsumer:
                    destination: topic-audit
                rabbit:
                    bindings:
                        output:
                            producer:
                                routingKeyExpression: headers.title
`

Thanks again for your advices
